apiVersion: v1
kind: Secret
metadata:
  name: nlwunite-secret
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU19GNWdsVS05TktDRG4wSXNuZnpYQG5sdy11bml0ZS1kby11c2VyLTE2Mjk5OTAzLTAuYy5kYi5vbmRpZ2l0YWxvY2Vhbi5jb206MjUwNjAvZGVmYXVsdGRiP3NzbG1vZGU9cmVxdWlyZQ==
